In [2]:
import cv2
import pandas as pd
import numpy as np

In [10]:
img = cv2.imread('data/1.jpeg',0)
print(img)

[[ 58  58  43 ... 178 170 175]
 [ 49  48  46 ... 176 176 178]
 [ 38  49  49 ... 169 170 170]
 ...
 [ 22  13  19 ...  15   9   5]
 [ 35  31  44 ...  34  36  27]
 [ 38  43  51 ...  36  34  42]]


In [17]:
cv2.imshow('data image', img)
key = cv2.waitKey(0) & 0xFF

#esc to remove and s press to save the picture 

if key==27:
    cv2.destroyAllWindows()
elif key == ord('s'):
    cv2.imwrite('copy.jpeg', img)
    cv2.destroyAllWindows()