In [57]:
import cv2 
import numpy as np 

In [60]:
# Webcamera no 0 is used to capture the frames 
cap = cv2.imread("../data/Fire2.jpg") 
cap = cv2.resize(cap,(400,300))

In [61]:
hsv = cv2.cvtColor(cap, cv2.COLOR_BGR2HSV) 

lower_red = np.array([0,121,167 ]) 
upper_red = np.array([38,232,255]) 

#experiment
filled_after = cap.copy()
cv2.drawContours(filled_after, [mask], 0, (0,255,0), -1)

#0,121,167  38,232,255
# Here we are defining range of bluecolor in HSV 
# This creates a mask of blue coloured 
# objects found in the frame. 
mask = cv2.inRange(hsv, lower_red, upper_red) 

# The bitwise and of the frame and mask is done so 
# that only the blue coloured objects are highlighted 
# and stored in res 
res = cv2.bitwise_and(cap,cap, mask= mask) 
print(res)
cv2.imshow('frame',cap) 
cv2.imshow('mask',mask) 
cv2.imshow('res',res) 

# This displays the frame, mask 
# and res which we created in 3 separate windows. 
k = cv2.waitKey(0) & 0xFF


# Destroys all of the HighGUI windows.
cv2.destroyAllWindows() 

# release the captured frame 
#cap.release() 


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
