In [1]:
import cv2
import pandas as pd
import numpy as np

In [2]:
img = cv2.imread('data/1.jpeg',0)
print(img)

[[ 58  58  43 ... 178 170 175]
 [ 49  48  46 ... 176 176 178]
 [ 38  49  49 ... 169 170 170]
 ...
 [ 22  13  19 ...  15   9   5]
 [ 35  31  44 ...  34  36  27]
 [ 38  43  51 ...  36  34  42]]


In [3]:
cv2.imshow('data image', img)
key = cv2.waitKey(0) & 0xFF

#esc to remove and s press to save the picture 

if key==27:
    cv2.destroyAllWindows()
elif key == ord('s'):
    cv2.imwrite('copy.jpeg', img)
    cv2.destroyAllWindows()

In [4]:
# video capture

cap = cv2.VideoCapture(0)    

In [5]:
while True:
    ret,frame = cap.read()
    
    cv2.imshow('frame',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [10]:
#for grayscaling
cap = cv2.VideoCapture(0)   


while cap.isOpened():
    ret,frame = cap.read()
    
    #for getting the frame size
    #print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    #print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cv2.imshow('frame',gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [11]:
#for saving
cap = cv2.VideoCapture(0)   

#for saving
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640,480))

while cap.isOpened():
    ret,frame = cap.read()
    
    if ret == True:
        cv2.imshow('frame',frame)
        out.write(frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()